### ISSUE TITLE
Can this be used as a relay?

### ISSUE THREAD

**Issue by beniffland** [sergey-brutsky/mi-home#17]
Hi Sergey,
I was wondering if this could be used to relay events from xiaomi devices to somewhere like Hubitat or WebCore? I use Xiaomi devices connected directly to Hubitat and SmartThings hubs but find that the xiaomi devices always drop their connections and the devices do not report back to the hubs in a timely enough manner. It would be more stable to use the actual Xiaomi Gateway hub and then relay the events from the devices to my other hubs. Do you think this would work?

thanks

**Comment by sergey-brutsky** [comment]
hi @beniffland, 

This library is helpful if you want to do custom actions triggered by xiaomi devices.
It has not been designed as a relay for events.
Theoretically it is possible to do it, but there is no such code yet.

If you want to relay events from your devices, in my point of view the easiest way would be to use xiaomi gateway that emits stream of events that you can listen from your code and forward to wherever you want.

Thanks,
Sergey

**Comment by ifflanb** [comment]
Thanks Sergey. When you say "use xiaomi gateway that emits stream of events that you can listen from your code", how would you listen for the events? Is that something that you can do in c#?

**Comment by sergey-brutsky** [comment]
Yes, it is possible to do form the c# code, take a look at https://github.com/sergey-brutsky/mi-home/blob/master/MiHomeLib/MiHome.cs#L121 
Here we are listening for "raw" events, parse them to objects and do useful things.
You can use this technique in your own code by forking the library and writing missing functionality

**Comment by ifflanb** [comment]
Thanks Sergey. I'll take a look. I think I noticed a comment to say that your code didn't work on the latest xiaomi gateway. Is that correct?

**Comment by sergey-brutsky** [comment]
Nope, manufacturer blocked ability to work with gateway programmatically in latest device versions (it doesn't emit any events to LAN). In order to unblock this ability an extra efforts needed, see README. It has no any relation to this library.

**Comment by sergey-brutsky** [comment]
@ifflanb was my answer helpful, do you need other help ?

**Comment by ifflanb** [comment]
HI yes very helpful thanks. I have ordered a version 2 gateway and will try to get it working when that arrives. Might be a while as I ordered from Ali Express :)

**Comment by sergey-brutsky** [comment]
Cool :)
