### ISSUE TITLE
Method Named

### ISSUE THREAD

**Issue by ifflanb** [sergey-brutsky/mi-home#18]
Hi, how do I discover which available methods there are for any given device please?
E.g gateway?.EnableLight() is one that you mention in your resdme but how do I find all methods that can be used? I am thinking about trying to use this for my Roborock s5 max vacuum.
Thanks Ben

**Comment by sergey-brutsky** [comment]
hi @ifflanb, roborock s5 max device is not supported at this moment.
Please take a look at this page to find all supported devices https://github.com/sergey-brutsky/mi-home/blob/master/README.md
Thanks

**Comment by sergey-brutsky** [comment]
Closed
