### ISSUE TITLE
Any plan to integrate 360 mi camera as a device ? 

### ISSUE THREAD

**Issue by sybaris** [sergey-brutsky/mi-home#19]
Hi,

Any plan to integrate 360 mi camera as a device ? 

Regards
Sybaris

**Comment by sergey-brutsky** [comment]
Hi @sybaris, I'm integrating devices that I have. 
I have plans to buy this camera but not in the nearest future.
It would be nice if you could provide a PR for integrating this camera into the library.

Thanks,
Sergey

**Comment by sybaris** [comment]
Hi,

I have the camera, but not the gateway.
I don't know how to get technical information about this camera...

Regards,
Sybaris

**Comment by sergey-brutsky** [comment]
Right now this library works only with devices negotiating via gateway.
I have plans to add support for other devices (that don't require gateway for they work).
Added 360 mi camera to my wishlist.

**Comment by sergey-brutsky** [comment]
Closed
