### ISSUE TITLE
Door/Window sensor or Aqara open/close sensor

### ISSUE THREAD

**Issue by vassiliss** [sergey-brutsky/mi-home#20]
I want to buy the Door/Window sensor and integrate it to my windows app. Do I need to buy also the Gateway or just the door sensor is enough?
Can you please enlighten me?

**Comment by sergey-brutsky** [comment]
Door/Windows sensor cannot work without Gateway.
I have to buy gateway also.

**Comment by vassiliss** [comment]
Thanks for the immediate response.
