### ISSUE TITLE
Can't reach any device

### ISSUE THREAD

**Issue by Ts1rke** [sergey-brutsky/mi-home#21]
Hi,

I tried your example code snippets but nothing happened. I tried to search for all devices, also tried to reach my gateway, but can't see anything (though I have a switch, a cube and a plug). How should these events work? For example when should the OnSocketPlug event fire exactly?
I checked your python script which you mentioned at an other issue, and I receive my gateway's heartbeats, so I guess I should reach it.

Thank you very much in advance,
Peter

**Comment by sergey-brutsky** [comment]
Hi, could you please show me what code snippet did you run ? 
Also please clarify where did you run your c# code and python code, from your laptop ?

**Comment by Ts1rke** [comment]
I tried exactly the example snippets from the readme file. I run the codes on my desktop PC which is connected with cable to the same network as the gateway.

**Comment by sergey-brutsky** [comment]
README file contains a lot of snippets.
Please show me the code that (possibly) is not working correctly and describe what exactly you want to achieve ? 
Do you want to turn on/off your socket plug ? Get events from the cube ?

**Comment by Ts1rke** [comment]
Primarily I would like to turn on/off the socket plug, but if I'd manage it to work, I would also do other stuff maybe. 

I've tried these for example:

The device searching:
```
public static void Main(string[] args)
{
    using var miHome = new MiHome();

    miHome.OnAnyDevice += (_, device) =>
    {
        Console.WriteLine($"{device.Sid}, {device.GetType()}, {device}");
    };

    Console.ReadLine();
}
```
The gateway light truning on/off:

```
public static void Main(string[] args)
{
    using var miHome = new MiHome();

    miHome.OnGateway += (_, gateway) =>
    {
        gateway.EnableLight();
        Task.Delay(3000).Wait();
        gateway.DisableLight();
    };
}
```

**Comment by sergey-brutsky** [comment]
Please make sure that:
1) Your gateway version is supported (DGNWG02LM)
2) Gateway ports are not blocked (udp port 9898 should be opened)
2) Your OS or any other installed software like (Virtual Box, Hyper-V, pcap) are not blocking UDP multicast traffic

**Comment by Ts1rke** [comment]
I can't find my gateway version, it isn't shown in the Mi Home app neither. Do you have any idea where to check it?
The ports aren't blocked, there is a firewall rule set to allow it and no software like these are running.

Side note: as I see, this description on Domoticz website isn't valid anymore as there is no About option in the gateway menu in the most recent Mi Home app. 😮 But I already had the token, so at least that isn't a problem.

The same (nothing) happens if I run the snippet with the token, but now I checked with Wireshark, and there is a communication.
When I start the application (more specifically when I declare the MiHome class), it sends a multicast message and I got a response for it directly to my PC's IP from the gateway's IP. This is received the data: 
`{"cmd":"get_id_list_ack","sid":"7c49eb88f719","token":"HJH5Va127DfnC2WO","data":"[\"158d0002c7f582\",\"158d00029aae2c\"]"}`
But I just see it with Wireshark, there isn't anything happening in my application.

**Comment by sergey-brutsky** [comment]
```
{"cmd":"get_id_list_ack","sid":"7c49eb88f719","token":"HJH5Va127DfnC2WO","data":"[\"158d0002c7f582\",\"158d00029aae2c\"]"}
```
This means that library is able to see 2 devices with sids from this array `[\"158d0002c7f582\",\"158d00029aae2c\"]`
and you can listen to events from this devices and send commands.
You mentioned that you want to work with "socket plug" device, a bit later I'll show you the code that is working on my PC

**Comment by Ts1rke** [comment]
Oh, I've just found the main problem... As I haven't seen any guide about this here, until now I've used .NET Framework (4.7.2) for trying the library, because I usually work with .NET Framework. But I've just noticed that your code must be written for .NET Core, so I tried that and now it works as it should be, yay!

Unfortunately I still can't reach my socket plug, as the two device what I can see is the cube and the switch. My plug looks exactly the same as the one you show in the readme. The only difference I noticed between the plug and the cube/switch in the Mi Home app is that the plug isn't a child device of the gateway. I tried to add it as a child device to the gateway to check if is it the problem, but I just can't configure it when I'm trying to add it as a child, only if I add it as a normal device separately from the gateway. Do you have your socket plug as a child device of your gateway, is it necessary? Do you have any further idea about this maybe?

**Comment by sergey-brutsky** [comment]
As far as I know there are two types of xiaomi smart socket plug: wifi version and zigbee version.
wifi version can work separately (no need to pair with gateway)
zigbee doesn't work as a separate device (need to pair with gateway)

I have only zigbee version of this adapter, this is the version that was implemented in this library.
If you have a desire to implement support for wifi version I will be happy.

**Comment by Ts1rke** [comment]
I see, I would happily implement that if I can for sure! Do you have any guideline or special instructions for that or do you think I could do that based on the implementation of other devices?

**Comment by sergey-brutsky** [comment]
As far as I know all wifi-based devices are implemented on top of MIIO protocol.
I recently started supporting this protocol.
The only device that I have right now that is working on top of MIIO is Mi Air Humidifier.
Please take a look at [the sources for this device](https://github.com/sergey-brutsky/mi-home/blob/master/MiHomeLib/Miio/AirHumidifier.cs), this might get a clue how to implement support for mi socket plug.
There is no special guideline/instructions at the moment, probably I'll add this instructions once the process settles down

**Comment by sergey-brutsky** [comment]
@Ts1rke if there are no other questions in this issue I suggest to close it

**Comment by Ts1rke** [comment]
Okay! I'll try to do the support for wifi version when I'll have time. Is there a way where I can reach you if I have questions about it?

**Comment by sergey-brutsky** [comment]
> Okay! I'll try to do the support for wifi version when I'll have time. Is there a way where I can reach you if I have questions about it?

Just create an issue and start the discussion
