### ISSUE TITLE
MiHome._devicesList is not thread-safe

### ISSUE THREAD

**Issue by jurgen-kluft** [sergey-brutsky/mi-home#3]
I have encountered an exception related to the device list that is owned by the class MiHome. After digging through the behaviour of this class and the async task(s) that add items to the list it is clear that exposing this list as public is dangerous. I have changed the code on my machine to use a ConcurrentDictionary<string, MiHomeDevice> where the key is the SID of the MiHomeDevice (which should be unique). So now adding devices is thread-safe when other places are using this collection.
Also the GetDevices() function returns a List<MiHomeDevice> which i construct from the concurrent dictionary before giving the list to the caller, like so: 
```List<MiHomeDevice> devices = _devicesList.Values.ToList()```

No problems so far.

**Comment by sergey-brutsky** [comment]
Hi, could you please elaborate a little bit on this. 
What exception did you get ? 
Using ConcurrentDictionary here is a bit overkill because there is exactly one thread that add/updates internal list of devices (not multipe threads). So it's not clear how could you get this exception.

Thanks

**Comment by jurgen-kluft** [comment]
You will get a runtime exception while iterating with foreach(MiHomeDevice device in devices) where the exception is informing you that the list has changed during the foreach.

The class MiHome has public functions to get all devices, device by name, device by SID. These functions take the _devicesList collection and use them. In the mean time there is a task running which processes incoming messages, some command also use the _devicesList and one of them is modifying the collection (UpdateDevicesList). 

You say you have only one thread and i guess you mean the async task 'StartReceivingMessages'?
However, creating and using the MiHome class is on another thread, so in effect we have 2 threads accessing _devicesList.

**Comment by sergey-brutsky** [comment]
Your arguments make sense.
Fixed issue in current master and shipped in next release --> https://www.nuget.org/packages/MiHomeLib/1.0.6

**Comment by sergey-brutsky** [comment]
@jurgen-kluft if fix is acceptible will close theissue
