### ISSUE TITLE
Will this work with Xiaomi Mi Smart Plug Wi-Fi (GMR4015GL) without a gateway?

### ISSUE THREAD

**Issue by AlsDevShack** [sergey-brutsky/mi-home#33]
Hi, I'm looking to buy a smart Power socket that I can control programmatically.
I'm wondering if this package will allow me to control "Xiaomi Mi Smart Plug Wi-Fi (GMR4015GL)" on it's own without a gateway device?

**Comment by sergey-brutsky** [comment]
hi @AlsDevShack, 
Mi Smart Plug is supported but only zigbee version.
Please contribute for supporting wifi version, as an example please take a look at [this](https://github.com/sergey-brutsky/mi-home/blob/master/MiHomeLib/Miio/AirHumidifier.cs) and [this](https://github.com/sergey-brutsky/mi-home/blob/master/MiHomeLib/Miio/MiRobotV1.cs) wifi devices

**Comment by sergey-brutsky** [comment]
Looks like no more actions needed
