### ISSUE TITLE
Gateway version 2.61.3

### ISSUE THREAD

**Issue by MicheleSondrio** [sergey-brutsky/mi-home#6]
After updating gateway to the latest avaible version (2.61.3) I can't find any device anymore... I tryed controlling if lan mode was still active, but there's no way to have the 2 more menus tapping on the version number. Any idea?

**Comment by sergey-brutsky** [comment]
I will take a look

**Comment by sergey-brutsky** [comment]
Hi, 
I've updated gateway plugin up to version 2.61.3 in my MiHome mobile app.
Eveything is working fine, I can see all my devices and send them commands.
I cannot reproduce your issue, could you please elaborate a bit ?

Thanks

**Comment by MicheleSondrio** [comment]
I'm really sorry for wasting your time. :-(
In gateway plugin 2.61.3 there's a much easier way to activate the "LAN mode": actually is call "Wireless Mode" and it's not hidden anymore.
My trouble was far away from that: in the same day I installed VirtualBox on my PC and the VirtualBox virtual network card was in some way conflicting with the UDP requests of Mi-Home-Lib.
Thank you for your patience and help.
