### ISSUE TITLE
Не отрабатывают EventHandler'ы

### ISSUE THREAD

**Issue by a-kryukov** [sergey-brutsky/mi-home#9]
Здравствуйте! 
Имеется следующая проблема. Инициализирую объект MiHome c паролем и сидом гейта. 
Определяются все подключенные к нему устройства. После подписки по сиду датчика влажности и температуры на события ничего не происходит.
`miHome = new MiHome("j3kvvz9x4ufgvyzr", "7c49eb88ce6f");
 Task.Delay(10000).Wait();
 var thSensor = miHome.GetDeviceBySid<ThSensor>("158d0002b54977");
 thSensor.OnHumidityChange += ThSensor_OnHumidityChange;
 thSensor.OnTemperatureChange += ThSensor_OnTemperatureChange;
`
события не файрятся =(
Помогите пожалуйста разобраться с проблемой. В какую сторону копать.

**Comment by sergey-brutsky** [comment]
Скорее всего у вас проблемы с сетью.
Так как gateway работает по протоколу udp multicast, важно чтобы машина на которой вы запускаете ваше приложение и сам gateway были в одном домене коллизий (грубо говоря в одной подсети).

Я рекомендую вам начать с простого, попробуйте просто отобразить в консоли все доступные девайсы которые вам отдаст gateway, пример кода смотрите на README странице

**Comment by sergey-brutsky** [comment]
@a-kryukov вам удалось решить проблему ?

**Comment by sergey-brutsky** [comment]
Закрыто за отсутствием активности
